import {defineStore} from 'pinia'
export const usePlayerInfo = defineStore('playerID', {
    
    state: () => ({
      selectedPID: "",
      scatterChart:[{"x": 59, "y": 89},
      {"x": 3, "y": 39},
      {"x": -58, "y": -85},
      {"x": -68, "y": 9},
      {"x": 33, "y": 26},
      {"x": -48, "y": 93},
      {"x": -16, "y": 98},
      {"x": -98, "y": -27},
      {"x": 62, "y": 1},
      {"x": -29, "y": 53},
      {"x": -67, "y": -30},
      {"x": -76, "y": 18},
      {"x": 91, "y": -96},
      {"x": -3, "y": 60},
      {"x": 1, "y": -69},
      {"x": 24, "y": -68},
      {"x": 76, "y": -8},
      {"x": -86, "y": -49},
      {"x": 79, "y": -38},
      {"x": 5, "y": -80},
      {"x": 1, "y": -44},
      {"x": 44, "y": 47},
      {"x": -99, "y": -36},
      {"x": -42, "y": 41},
      {"x": -27, "y": -85},
      {"x": 34, "y": -78},
      {"x": 17, "y": 26},
      {"x": -43, "y": -21},
      {"x": -73, "y": 82},
      {"x": 69, "y": 41},
      {"x": -78, "y": 57},
      {"x": 39, "y": -96},
      {"x": 12, "y": -72},
      {"x": -44, "y": -66},
      {"x": 16, "y": 70},
      {"x": 61, "y": 89},
      {"x": -80, "y": 67},
      {"x": -89, "y": 99},
      {"x": -26, "y": 70},
      {"x": 58, "y": -87},
      {"x": 5, "y": -20},
      {"x": -28, "y": 51},
      {"x": -7, "y": -79},
      {"x": -7, "y": 90},
      {"x": -44, "y": 51},
      {"x": -55, "y": -98},
      {"x": -64, "y": 11},
      {"x": 20, "y": -40},
      {"x": 40, "y": -51},
      {"x": 45, "y": -45},
      {"x": 45, "y": -91},
      {"x": -100, "y": 10},
      {"x": 38, "y": 70},
      {"x": -3, "y": -17},
      {"x": 98, "y": 68},
      {"x": -19, "y": 52},
      {"x": 24, "y": -51},
      {"x": 3, "y": 17},
      {"x": 40, "y": -92},
      {"x": -3, "y": 98},
      {"x": 90, "y": -67},
      {"x": -41, "y": 1},
      {"x": 78, "y": 83},
      {"x": 20, "y": -99},
      {"x": 2, "y": -75},
      {"x": -70, "y": 47},
      {"x": -83, "y": -55},
      {"x": 33, "y": -79},
      {"x": -69, "y": -100},
      {"x": -3, "y": -88},
      {"x": -13, "y": 39},
      {"x": 53, "y": 22},
      {"x": 52, "y": 100},
      {"x": -76, "y": 42},
      {"x": -69, "y": -40},
      {"x": 88, "y": -54},
      {"x": -25, "y": -49},
      {"x": 0, "y": -18},
      {"x": 27, "y": 63},
      {"x": -21, "y": 85},
      {"x": 20, "y": 55},
      {"x": 43, "y": 34},
      {"x": -47, "y": 43},
      {"x": 50, "y": -31},
      {"x": -22, "y": 38},
      {"x": -33, "y": 31},
      {"x": 88, "y": 52},
      {"x": -96, "y": 20},
      {"x": -28, "y": 89},
      {"x": -15, "y": 17},
      {"x": -18, "y": 54},
      {"x": 69, "y": -21},
      {"x": 62, "y": -33},
      {"x": 34, "y": 95},
      {"x": -2, "y": -43},
      {"x": -14, "y": 12},
      {"x": -50, "y": -13},
      {"x": 87, "y": -44},
      {"x": 75, "y": 29},
      {"x": -39, "y": -63},
      {"x": -92, "y": -88},
      {"x": -100, "y": -34},
      {"x": 91, "y": 28},
      {"x": 40, "y": 22},
      {"x": -45, "y": -28},
      {"x": 98, "y": -15},
      {"x": -53, "y": 25},
      {"x": -82, "y": -47},
      {"x": -57, "y": -60},
      {"x": 4, "y": -28},
      {"x": 78, "y": -73},
      {"x": -25, "y": -96},
      {"x": -5, "y": -14},
      {"x": 59, "y": 40},
      {"x": -90, "y": 45},
      {"x": 11, "y": -55},
      {"x": -77, "y": 95},
      {"x": -32, "y": -11},
      {"x": 97, "y": 27},
      {"x": -48, "y": 58},
      {"x": -85, "y": 63},
      {"x": 71, "y": -47},
      {"x": -21, "y": -72},
      {"x": -67, "y": 98},
      {"x": 29, "y": 76},
      {"x": 5, "y": 4},
      {"x": -43, "y": -2},
      {"x": 6, "y": 92},
      {"x": 23, "y": -60},
      {"x": -78, "y": -8},
      {"x": 47, "y": 63},
      {"x": -15, "y": -25},
      {"x": -98, "y": -99},
      {"x": -64, "y": -71},
      {"x": 28, "y": 65},
      {"x": 99, "y": 73},
      {"x": -44, "y": -46},
      {"x": 37, "y": -92},
      {"x": -1, "y": -49},
      {"x": 91, "y": -92},
      {"x": -100, "y": 55},
      {"x": -52, "y": 23},
      {"x": -31, "y": 20},
      {"x": 47, "y": -29},
      {"x": -66, "y": -82},
      {"x": -35, "y": -94},
      {"x": 30, "y": 18},
      {"x": -60, "y": -51},
      {"x": 82, "y": -4},
      {"x": -8, "y": -77},
      {"x": -71, "y": -22},
      {"x": 86, "y": 91},
      {"x": -55, "y": -9},
      {"x": 59, "y": 89},
      {"x": 3, "y": 39},
      {"x": -58, "y": -85},
      {"x": -68, "y": 9},
      {"x": 33, "y": 26},
      {"x": -48, "y": 93},
      {"x": -16, "y": 98},
      {"x": -98, "y": -27},
      {"x": 62, "y": 1},
      {"x": -29, "y": 53},
      {"x": -67, "y": -30},
      {"x": -76, "y": 18},
      {"x": 91, "y": -96},
      {"x": -3, "y": 60},
      {"x": 1, "y": -69},
      {"x": 24, "y": -68},
      {"x": 76, "y": -8},
      {"x": -86, "y": -49},
      {"x": 79, "y": -38},
      {"x": 5, "y": -80},
      {"x": 1, "y": -44},
      {"x": 44, "y": 47},
      {"x": -99, "y": -36},
      {"x": -42, "y": 41},
      {"x": -27, "y": -85},
      {"x": 34, "y": -78},
      {"x": 17, "y": 26},
      {"x": -43, "y": -21},
      {"x": -73, "y": 82},
      {"x": 69, "y": 41},
      {"x": -78, "y": 57},
      {"x": 39, "y": -96},
      {"x": 12, "y": -72},
      {"x": -44, "y": -66},
      {"x": 16, "y": 70},
      {"x": 61, "y": 89},
      {"x": -80, "y": 67},
      {"x": -89, "y": 99},
      {"x": -26, "y": 70},
      {"x": 58, "y": -87},
      {"x": 5, "y": -20},
      {"x": -28, "y": 51},
      {"x": -7, "y": -79},
      {"x": -7, "y": 90},
      {"x": -44, "y": 51},
      {"x": -55, "y": -98},
      {"x": -64, "y": 11},
      {"x": 20, "y": -40},
      {"x": 40, "y": -51},
      {"x": 45, "y": -45},
      {"x": 45, "y": -91},
      {"x": -100, "y": 10},
      {"x": 38, "y": 70},
      {"x": -3, "y": -17},
      {"x": 98, "y": 68},
      {"x": -19, "y": 52},
      {"x": 24, "y": -51},
      {"x": 3, "y": 17},
      {"x": 40, "y": -92},
      {"x": -3, "y": 98},
      {"x": 90, "y": -67},
      {"x": -41, "y": 1},
      {"x": 78, "y": 83},
      {"x": 20, "y": -99},
      {"x": 2, "y": -75},
      {"x": -70, "y": 47},
      {"x": -83, "y": -55},
      {"x": 33, "y": -79},
      {"x": -69, "y": -100},
      {"x": -3, "y": -88},
      {"x": -13, "y": 39},
      {"x": 53, "y": 22},
      {"x": 52, "y": 100},
      {"x": -76, "y": 42},
      {"x": -69, "y": -40},
      {"x": 88, "y": -54},
      {"x": -25, "y": -49},
      {"x": 0, "y": -18},
      {"x": 27, "y": 63},
      {"x": -21, "y": 85},
      {"x": 20, "y": 55},
      {"x": 43, "y": 34},
      {"x": -47, "y": 43},
      {"x": 50, "y": -31},
      {"x": -22, "y": 38},
      {"x": -33, "y": 31},
      {"x": 88, "y": 52},
      {"x": -96, "y": 20},
      {"x": -28, "y": 89},
      {"x": -15, "y": 17},
      {"x": -18, "y": 54},
      {"x": 69, "y": -21},
      {"x": 62, "y": -33},
      {"x": 34, "y": 95},
      {"x": -2, "y": -43},
      {"x": -14, "y": 12},
      {"x": -50, "y": -13},
      {"x": 87, "y": -44},
      {"x": 75, "y": 29},
      {"x": -39, "y": -63},
      {"x": -92, "y": -88},
      {"x": -100, "y": -34},
      {"x": 91, "y": 28},
      {"x": 40, "y": 22},
      {"x": -45, "y": -28},
      {"x": 98, "y": -15},
      {"x": -53, "y": 25},
      {"x": -82, "y": -47},
      {"x": -57, "y": -60},
      {"x": 4, "y": -28},
      {"x": 78, "y": -73},
      {"x": -25, "y": -96},
      {"x": -5, "y": -14},
      {"x": 59, "y": 40},
      {"x": -90, "y": 45},
      {"x": 11, "y": -55},
      {"x": -77, "y": 95},
      {"x": -32, "y": -11},
      {"x": 97, "y": 27},
      {"x": -48, "y": 58},
      {"x": -85, "y": 63},
      {"x": 71, "y": -47},
      {"x": -21, "y": -72},
      {"x": -67, "y": 98},
      {"x": 29, "y": 76},
      {"x": 5, "y": 4},
      {"x": -43, "y": -2},
      {"x": 6, "y": 92},
      {"x": 23, "y": -60},
      {"x": -78, "y": -8},
      {"x": 47, "y": 63},
      {"x": -15, "y": -25},
      {"x": -98, "y": -99},
      {"x": -64, "y": -71},
      {"x": 28, "y": 65},
      {"x": 99, "y": 73},
      {"x": -44, "y": -46},
      {"x": 37, "y": -92},
      {"x": -1, "y": -49},
      {"x": 91, "y": -92},
      {"x": -100, "y": 55},
      {"x": -52, "y": 23},
      {"x": -31, "y": 20},
      {"x": 47, "y": -29},
      {"x": -66, "y": -82},
      {"x": -35, "y": -94},
      {"x": 30, "y": 18},
      {"x": -60, "y": -51},
      {"x": 82, "y": -4},
      {"x": -8, "y": -77},
      {"x": -71, "y": -22},
      {"x": 86, "y": 91},
      {"x": -55, "y": -9},

      ] ,
      playerIDs: [
        {
          "id": "001",
          "name": "GreenNinja#2212",
          "deathPosX": 159,
          "deathPosY": 250,
          "matchID": 467,
          "wins": 274,
          "losses": 365,
          "draws": 369,
          "solo": 101,
          "coop": 226,
          "tournament": 257,
          "kills": 176,
          "assists": 433,
          "deaths": 155,
          "shotAccuracy": "82%",
          "revives": 120,
          "headshots": 300,
          "meleeKills": 45,
          "flagCaptures": 67,
          "flagReturns": 34,
          "flagRetrieved": 77,
          "bombsDefused": 20,
          "bombsPlanted": 25,
          "bombsStolen": 120,
          "sniperKills": 80,
          "killStreaks": 15
        },
        {
          "id": "002",
          "name": "YourMom#1435254",
          "deathPosX": 356,
          "deathPosY": 274,
          "matchID": 477,
          "wins": 427,
          "losses": 52,
          "draws": 230,
          "solo": 72,
          "coop": 331,
          "tournament": 57,
          "kills": 432,
          "assists": 486,
          "deaths": 290,
          "shotAccuracy": "71%",
          "revives": 95,
          "headshots": 250,
          "meleeKills": 30,
          "flagCaptures": 52,
          "flagReturns": 29,
          "flagRetrieved": 122,
          "bombsDefused": 15,
          "bombsPlanted": 18,
          "bombsStolen": 8,
          "sniperKills": 60,
          "killStreaks": 20
        },
        {
          "id": "003",
          "name": "KamarTaj#1316",
          "deathPosX": 422,
          "deathPosY": 267,
          "matchID": 481,
          "wins": 443,
          "losses": 429,
          "draws": 435,
          "solo": 551,
          "coop": 12,
          "tournament": 231,
          "kills": 259,
          "assists": 265,
          "deaths": 476,
          "shotAccuracy": "84%",
          "revives": 200,
          "headshots": 320,
          "meleeKills": 50,
          "flagCaptures": 75,
          "flagReturns": 40,
          "flagRetrieved": 91,
          "bombsDefused": 22,
          "bombsPlanted": 30,
          "bombsStolen": 158,
          "sniperKills": 90,
          "killStreaks": 25
        },
        {
          "id": "004",
          "name": "Rice4Life",
          "deathPosX": 426,
          "deathPosY": 107,
          "matchID": 356,
          "wins": 288,
          "losses": 413,
          "draws": 63,
          "solo": 115,
          "coop": 66,
          "tournament": 421,
          "kills": 140,
          "assists": 77,
          "deaths": 432,
          "shotAccuracy": "85%",
          "revives": 134,
          "headshots": 285,
          "meleeKills": 55,
          "flagCaptures": 81,
          "flagReturns": 47,
          "flagRetrieved": 24,
          "bombsDefused": 27,
          "bombsPlanted": 33,
          "bombsStolen": 56,
          "sniperKills": 70,
          "killStreaks": 18
        },
        {
          "id": "005",
          "name": "StealthMaster#528",
          "deathPosX": 214,
          "deathPosY": 312,
          "matchID": 502,
          "wins": 312,
          "losses": 390,
          "draws": 158,
          "solo": 200,
          "coop": 312,
          "tournament": 158,
          "kills": 312,
          "assists": 158,
          "deaths": 390,
          "shotAccuracy": "78%",
          "revives": 158,
          "headshots": 390,
          "meleeKills": 78,
          "flagCaptures": 312,
          "flagReturns": 200,
          "flagRetrieved": 112,
          "bombsDefused": 39,
          "bombsPlanted": 78,
          "bombsStolen": 51,
          "sniperKills": 158,
          "killStreaks": 39
        },
        {
          "id": "006",
          "name": "NightHawk#359",
          "deathPosX": 158,
          "deathPosY": 214,
          "wins": 214,
          "losses": 158,
          "draws": 312,
          "solo": 359,
          "coop": 214,
          "tournament": 312,
          "kills": 519,
          "assists": 359,
          "deaths": 214,
          "shotAccuracy": "83%",
          "headshots": 519,
          "meleeKills": 83,
          "flagCaptures": 359,
          "flagReturns": 214,
          "flagRetrieved": 87,
          "bombsDefused": 83,
          "bombsPlanted": 158,
          "bombsStolen": 44,
          "sniperKills": 214,
          "killStreaks": 83,
          "revives": 214,
          "matchID": 519,
        },
      ],
           
    }), 

    getters: {

      pSelectedPlayer: (state) => {
        return state.playerIDs.find(p => p.id === state.selectedPID) || null
      },

      pStreaks: (state) => {
        const player = state.pSelectedPlayer
        return player ? { TripleKills: player.matchID, QuadKills: player.revives, PentaKills: player.killStreaks} : null
      },

      pGetKillTypes: (state) => {
        const player = state.pSelectedPlayer
        return player ? { Headshots: player.headshots, MeleeKills: player.meleeKills, SniperKills: player.sniperKills} : null
      },

      pBomb: (state) => {
        const player = state.pSelectedPlayer
        return player ? { Headshots: player.headshots, MeleeKills: player.meleeKills, SniperKills: player.sniperKills} : null
      },

      pGetFlagstats: (state) => {
        const player = state.pSelectedPlayer
        return player ? { FlagsRetrieved: player.flagRetrieved, FlagReturns: player.flagReturns, FlagCaptures: player.flagCaptures} : null
      },

      pGetGameModes: (state) => {
        const player = state.pSelectedPlayer
        return player ? { Solo: player.solo, Co_op: player.coop, Tournament: player.tournament} : null
      },

      pGetKDA: (state) => {
        const player = state.pSelectedPlayer
        return player ? { Wins: player.wins, Losses: player.losses, Draws: player.draws} : null
      }, 

      pShotAcc: (state) => {
        const player = state.pSelectedPlayer
        return player ? player.shotAccuracy: null
      }, 

      pRadarChartData: (state) => {
        const player = state.pSelectedPlayer
        return player ? { Kills: player.kills, Assists: player.assists, Deaths: player.deaths} : null
      }
    }, 

    actions: {
      updateStat({statId, value}) {
        const player = this.pSelectedPlayer
        if (player && statId in player){
          player[statId] = value; 
        }
        else {
          console.error('Stat or player not valid')
        }
      },
      pSetSelectedPID(id) {
        this.selectedPID = id;
      },

      pDeathPosX(value) {
        const player = this.pSelectedPlayer
        if (player) {
          if (value !== undefined) player.deathPosX = value
        }
      },
      
      pDeathPosY(value) {
        const player = this.pSelectedPlayer
        if (player) {
          if (value !== undefined) player.deathPosY = value
        }
      },

      pWins(value) {
        const player = this.pSelectedPlayer
        if (player) {
          if (value !== undefined) player.wins = value
        }
      },
      pLosses(value) {
        const player = this.pSelectedPlayer
        if (player) {
          if (value !== undefined) player.losses = value
        }
      },
 
      pDraws(value) {
        const player = this.pSelectedPlayer
        if (player) {
          if (value !== undefined) player.draws = value
        }
      },
      pKills(value) {
        const player = this.pSelectedPlayer
        if (player) {
          if (value !== undefined) player.kills = value
        }
      },
      pDeaths(value) {
        const player = this.pSelectedPlayer
        if (player) {
          if (value !== undefined) player.deaths = value
        }
      },
      pAssists(value) {
        const player = this.pSelectedPlayer
        if (player) {
          if (value !== undefined) player.assists = value
        }
      },
 
    }
})